### ISSUE TITLE
[Bug] Dragonfire makes wings disappear.

### ISSUE THREAD

**Issue by ToothlessAsh** [pau101/Wings#68] opened 2020-12-02 08:42 UTC
I don't know why but when I play Dragonfire by Tiny Turtle the wings don't load and there's no sound for them. Is this a problem with the models clashing or something else?

**Comment by pau101** [comment] 2020-12-06 04:23
Thanks for reporting!

However, this seems to be a duplicate of #64 and this is an issue on their end.

**Closed by pau101** 2020-12-06 04:23 UTC
