### ISSUE TITLE
SpongeForge not working with Wings mod!

### ISSUE THREAD

**Issue by MaxIsH0t** [pau101/Wings#34] opened 2019-06-15 21:00 UTC
Forge Version: forge-1.12.2-14.23.5.2838-universal
Sponge Version:  spongeforge-1.12.2-2825-7.1.6
Wings Version: wings-1.1.2-1.12.2

I am trying to run the wings mod with sponge but it doesn't want to work.

Latest log: https://hastebin.com/abifaboxeh.sql

**Comment by LemADEC** [comment] 2019-07-21 10:08
llibrary-1.0.10-1.12.2 is outdated
Issue isn't reproduced with llibrary-1.7.19-1.12.2 + wings-1.1.5-1.12.2 + spongeforge-1.12.2-2838-7.1.7-RC3841
You may close this issue

**Comment by pau101** [comment] 2019-07-22 01:03
Ah yes, this was from a known issue in llibrary which has since been fixed.

**Closed by pau101** 2019-07-22 01:03 UTC
